---
title: "data_import"
author: "Tiffany Xi"
date: 2018-09-18
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```
absolute path
relative path better-stable


## Import FAS csv files

import my first csv
r package::function inside the package
if two package have same function---conflict

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)
```

Import the pups data also

```{r}
#absolute path
pups_data = read_csv(file = "/Users/apple/Desktop/DataScience/Lecture5/data_wrangling/data/FAS_pups.csv")
pups_data = read_csv(file = "~/Desktop/DataScience/Lecture5/data_wrangling/data/FAS_pups.csv")

#relative path
pups_data = read_csv(file = "./data/FAS_pups.csv")
```

##Look at the data

look at litters data

```{r}
litters_data

head(litters_data)
tail(litters_data, 5)

skimr::skim(litters_data)

#View(litters_data)
#all of the data//cannot knit


```

Skip some rows

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv", skip = 10, col_names = FALSE)
```

```{r}
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = cols(
    Group = col_character(),
    `Litter Number` = col_character(),
    `GD0 weight` = col_double(),
    `GD18 weight` = col_double(),
    `GD of Birth` = col_integer(),
    `Pups born alive` = col_integer(),
    `Pups dead @ birth` = col_integer(),
    `Pups survive` = col_integer()
  )
)
tail(litters_data)

#shorthand for almost every data type
litters_data = read_csv(file = "./data/FAS_litters.csv",
  col_types = "ccddiiii"
)
head(litters_data)

```


```{r}
pups_data = read_csv(file = "./data/FAS_pups.csv",
                     col_types = "ciiiii"
                     )
pups_data = janitor::clean_names(pups_data)
skimr::skim(pups_data)
```


##Other formats

Read in mlb data

```{r}
mlb_data = readxl::read_excel(path = "./data/mlb11.xlsx", n_max = 20)
tail(mlb_data, 5)

mlb_subset = readxl::read_excel(path = "./data/mlb11.xlsx", range = "A1:E17")
tail(mlb_subset)
```

Read in the pulse data

SAS dataset
```{r}
pulse_data = haven::read_sas("./data/public_pulse_data.sas7bdat")
pulse_data
```

##Compare with base R

```{r}
pups_base = read.csv("./data/FAS_pups.csv")
pups_readr = read_csv("./data/FAS_pups.csv")
pups_base$S
pups_readr$S #error
```


